--fPedidosDeVenda
SELECT
	pv.PEDIDOV AS PEDIDO_ID,
	pv.N_PEDIDO_CLIENTE,
	pv.COD_PEDIDOV,
	pv.DATA_EMISSAO AS DATA_EMISSAO_PEDIDO,
	pv.ORIGEM_PEDIDO,
	tp2.DESCRICAO AS TIPO_PEDIDO,
	f.COD_FILIAL AS FILIAL_COD,
	f.FANTASIA AS FILIAL_FANTASIA,
	pv.ORCAMENTO,
	pv.EFETUADO,
	pv.APROVADO,
	pv.ENVIADO,
	pv.ENTREGUE,
	pv.STATUS_WORKFLOW AS COD_STATUS_WORKFLOW,
	sw.DESCRICAO AS DESC_STATUS_WORKFLOW,
	gl.COD_GRUPO AS COD_GRUPO_LOJA,
	gl.NOME AS GRUPO_LOJA_FANTASIA,
	pv.CLIENTE,
	c.COD_CLIENTE,
	pv.COD_ENDERECO,
	c.NOME AS CLIENTE_NOME_RAZAO,
	c.FANTASIA AS CLIENTE_FANTASIA,
	c.CNPJ,
	c.CPF,
	r.COD_REPRESENTANTE,
	r.NOME AS REPRESENTANTE_NOME_RAZAO,
	r.E_MAIL AS REPRESENTANTE_EMAIL,
	tp.COD_TPRECO AS TPRECO_COD,
	tp.DESCRICAO AS TPRECO_NOME,
	t.NOME AS TRANSPORTADORA,
	pv.MODALIDADE_FRETE,
	cp.CODIGO AS CONDICOES_PGTO_COD,
	cp.DESCRICAO AS CONDICOES_PGTO_DESC,
	p.COD_PRODUTO AS SKU1,
	c2.COD_COR,
	pp.TAMANHO,
	tp.COD_TPRECO || p.COD_PRODUTO AS KEY_TABPRICE,
	pp.QUANTIDADE,
	pp.ENTREGUE AS QUANTIDADE_PREFAT,
	pp.RESERVADO,
	pp.PREFATURAMENTO,
	pp.PRECO AS PRECO_PEDIDOV,
	(pp.PRECO - pp.PRECO * ((100 + pv.acerto)/100)) AS DESCONTO_ITEM,
	(pp.PRECO * ((100 + pv.acerto)/100)) AS PRECO_COMDESCONTO_PEDIDOV,
	pv.ACERTO,
	pv.CORTESIA,
	(pp.QUANTIDADE * (pp.PRECO * ((100 + pv.acerto)/100))) AS VALOR_PEDIDOV,
	(pp.ENTREGUE * (pp.PRECO * ((100 + pv.acerto)/100))) AS VALOR_PEDIDOV_PREFAT,
	pp.MOTIVO_CANC,
	pp.OBS_CANC,
	p.COD_PRODUTO||'-'||c2.COD_COR||'-' AS PRODUTO_SKU2,
	p.COD_PRODUTO||'-'||c2.COD_COR||'-'||pp.TAMANHO AS PRODUTO_SKU3,
	p.PRODUTO||'_'||c2.COR||'_'||'0'||'_'||pp.TAMANHO AS PRODUTO_ID_INTERNO
FROM PEDIDO_VENDA pv 
JOIN FILIAIS f ON f.FILIAL = pv.FILIAL
JOIN CLIENTES c ON c.CLIENTE = pv.CLIENTE
LEFT JOIN GRUPO_LOJAS gl ON gl.GRUPO_LOJA = c.GRUPO_LOJA
LEFT JOIN TIPOS_PEDIDO tp2 ON tp2.TIPO_PEDIDO = pv.TIPO_PEDIDO
LEFT JOIN REPRESENTANTES r ON r.REPRESENTANTE = pv.REPRESENTANTE
LEFT JOIN PRODUTO_PEDIDOV pp ON pp.PEDIDOV = pv.PEDIDOV
LEFT JOIN PRODUTOS p ON p.PRODUTO = pp.PRODUTO
LEFT JOIN CORES c2 ON c2.COR = pp.COR
LEFT JOIN CONDICOES_PGTO cp ON cp.CONDICOES_PGTO = pv.CONDICOES_PGTO
LEFT JOIN TABELAS_PRECO tp ON tp.TABELA = pv.TABELA
LEFT JOIN TRANSPORTADORAS t ON t.TRANSPORTADORA = pv.TRANSPORTADORA
LEFT JOIN STATUS_WORKFLOW sw ON sw.STATUS_WORKFLOW = pv.STATUS_WORKFLOW
