SELECT
    p.COD_PRODUTO
    ,REPLACE(REPLACE(cb.BARRA, ASCII_CHAR(10), ''), ASCII_CHAR(13), '') AS BARRA_REPLACE
    ,cb.*
FROM
    CODIGO_BARRAS cb
    LEFT JOIN PRODUTOS p ON p.PRODUTO = cb.PRODUTO
WHERE
    p.COD_PRODUTO = 'ABCDEFG'

-------

UPDATE CODIGO_BARRAS cb
SET cb.BARRA = REPLACE(REPLACE(cb.BARRA, ASCII_CHAR(10), ''), ASCII_CHAR(13), '')
WHERE cb.BARRA IS NOT NULL
