--ClienteBloqueados
SELECT 
c.DESATIVADO,
c.BLOQUEIA_VENDAS,
c.BLOQUEIA_PEDIDOS,
c.BLOQUEIO_STATUS,
c.COD_CLIENTE
FROM CLIENTES c
WHERE c.PF_PJ = 'PJ' AND c.BLOQUEIA_VENDAS = 'T'

--UPDATE ClienteBloqueados
UPDATE CLIENTES c SET c.BLOQUEIA_VENDAS = 'F' WHERE c.PF_PJ = 'PJ' AND c.BLOQUEIA_VENDAS = 'T'
