--Clientes
SELECT 
	c.GERADOR,
	i.CLIENTE,
	c.COD_CLIENTE,
	c.NOME AS NOME_RAZAO_SOCIAL,
	c.FANTASIA,
	gl.GRUPO_LOJA,
	gl.COD_GRUPO AS COD_GRUPO_LOJA,
	gl.NOME AS NOME_GRUPO_LOJA,
	c.PF_PJ,
	c.CNPJ,
	c.IE,
	c.CPF,
	c.E_MAIL,
	c.E_MAIL_NFE,
	t.NOME AS TRANSPORTADORA,
	tf.DESCRICAO AS TIPO_FRETE_DESCRICAO,
	r.NOME AS CONSULTOR,
	r.E_MAIL AS CONSULTOR_EMAIL,
	ec.ESTADO,
	ec.CIDADE,
	ui.UFCOD AS COD_IBGE_UF,
	m.COD_IBGE AS COD_IBGE_MUN,
	ec.BAIRRO,
	ec.LOGRADOURO,
	ec.NUMERO,
	ec.COMPLEMENTO,
	ec.CEP,
	ucmcp.CODIGO AS MACRO_CLASSE_PDV_INDEX,
	ucmcp.DESCRICAO AS MACRO_CLASSE_PDV,
	uccp.CODIGO AS CLASSE_PDV_INDEX,
	uccp.DESCRICAO AS CLASSE_PDV,
	ucpp.CODIGO AS PERFIL_PDV_INDEX,
	ucpp.DESCRICAO AS PERFIL_PDV,
	ucsp.CODIGO AS SEGMENTO_PDV_INDEX,
	ucsp.DESCRICAO AS SEGMENTO_PDV,
	urmc.CODIGO AS MACRO_COB_CONSULTOR_INDEX,
	urmc.DESCRICAO AS MACRO_COB_CONSULTOR,
	urmc2.CODIGO AS MICRO_COB_CONSULTOR_INDEX,
	urmc2.DESCRICAO AS MICRO_COB_CONSULTOR
FROM CLIENTES c 
LEFT JOIN ICLIENTES i ON i.GERADOR = c.GERADOR
LEFT JOIN ITRANSPORTADORAS it ON it.TRANSPORTADORA = c.TRANSPORTADORA
LEFT JOIN TRANSPORTADORAS t ON t.GERADOR = it.GERADOR
LEFT JOIN TIPOS_FRETE tf ON tf.TIPO_FRETE = c.TIPO_FRETE 
LEFT JOIN GRUPO_LOJAS gl ON gl.GRUPO_LOJA = c.GRUPO_LOJA 
LEFT JOIN REPRESENTANTES r ON r.REPRESENTANTE = c.REPRESENTANTE
LEFT JOIN ENDERECOS_CADASTRO ec ON c.GERADOR = ec.GERADOR AND ec.ENDERECO_NOTA = 'T'
LEFT JOIN UF_IBGE ui ON ui.UFSIGLA = ec.ESTADO
LEFT JOIN MUNICIPIOS m ON m.NOME_SEM_ACENTO = ec.CIDADE AND m.UF = ec.ESTADO 
LEFT JOIN USR_CLIENTES_MACRO_CLASSE_PDV ucmcp ON ucmcp.CLIENTE = c.CLIENTE 
LEFT JOIN USR_CLIENTES_CLASSE_PDV uccp ON uccp.CLIENTE = c.CLIENTE
LEFT JOIN USR_CLIENTES_PERFIL_PDV ucpp ON ucpp.CLIENTE = c.CLIENTE
LEFT JOIN USR_CLIENTES_SEGMENTO_PDV ucsp ON ucsp.CLIENTE = c.CLIENTE
LEFT JOIN USR_REP_MACRO_COBERTURA urmc ON urmc.REPRESENTANTE = c.REPRESENTANTE
LEFT JOIN USR_REP_MICRO_COBERTURA urmc2 ON urmc2.REPRESENTANTE = c.REPRESENTANTE
ORDER BY c.COD_CLIENTE ASC
