--Produtos
SELECT 
	p.PRODUTO AS PRODUTO_CODIGO,
	p.DESCRICAO1 AS PRODUTO_DESCRICAO,
	m.COD_MARCA AS COD_PRODUTO_MARCA,
	m.DESCRICAO AS PRODUTO_MARCA,
	d.COD_DIVISAO AS COD_PRODUTO_COLECAO_BINARIA,
	d.DESCRICAO AS PRODUTO_COLECAO_BINARIA,
	c2.COD_COLECAO AS COD_PRODUTO_COLECAO,
	c2.DESCRICAO AS PRODUTO_COLECAO,
	s.COD_SUBCOLECAO AS COD_PRODUTO_SUBCOLECAO,
	s.DESCRICAO AS PRODUTO_SUBCOLECAO,
	uplp.CODIGO AS COD_PRODUTO_LINHA_PERFORMANCE,
	uplp.DESCRICAO AS PRODUTO_LINHA_PERFORMANCE,
	c3.COD_CATEGORIA AS COD_PRODUTO_LINHA,
	c3.DESCRICAO AS PRODUTO_LINHA,
	d2.COD_DEPARTAMENTO AS COD_PRODUTO_SUBLINHA,
	d2.DESCRICAO AS PRODUTO_SUBLINHA,
	upo.CODIGO AS COD_PRODUTO_ORIENTACAO,
	upo.DESCRICAO AS PRODUTO_ORIENTACAO,
	t2.COD_TIPO AS COD_PRODUTO_TIPO,
	t2.DESCRICAO AS PRODUTO_TIPO,
	fv.CODIGO AS COD_PRODUTO_SUBTIPO,
	fv.DESCRICAO AS PRODUTO_SUBTIPO,
	p.COD_PRODUTO AS PRODUTO_SKU1,
	c.COR AS PRODUTO_COR_ID,
	c.COD_COR AS PRODUTO_COR_CODIGO,
	c.DESCRICAO AS PRODUTO_COR_DESCRICAO,
	ucct.DESCRICAO AS PRODUTO_COLECAO_TEMA,
	ucp2.DESCRICAO AS PRODUTO_COR_PRIMARIA,
	ucs.DESCRICAO AS PRODUTO_COR_SECUNDARIA,
	ueep.DESCRICAO AS PRODUTO_COR_ESTAMPA_PRIMARIA,
	uees.DESCRICAO AS PRODUTO_COR_ESTAMPA_SECUNDARIA,
	t.TAMANHO AS PRODUTO_TAMANHO,
	g.COD_GRADE AS COD_PRODUTO_GRADE,
	g.DESCRICAO AS PRODUTO_GRADE,
	cb.BARRA AS GTIN,
	p.OBS,
	p.LARGURA,
	p.COMPRIMENTO,
	p.ALTURA,
	p.PESO,
	cf.DESCRICAO AS NCM,
	g2.COD_GRUPO AS COD_PRODUTO_GRUPO,
	g2.DESCRICAO AS PRODUTO_GRUPO,
	uad.COLECAOBINARIA_ENGLISH AS PRODUCT_COLLECTION_BIN,
	uac.COLECAO_ENGLISH  AS PRODUCT_COLLECTION,
	uas.SUBCOLECAO_ENGLISH AS PRODUCT_SUB_COLLECTION,
	uat.TIPO_ENGLISH AS PRODUCT_TYPE,
	ucp.MODELO_ENGLISH,
	ct.DESCRICAO AS PRODUCT_COLOR,
	tt.DESCRICAO AS PRODUCT_SIZE,
	ucp.HEIGHT_INCHES,
	ucp.WIDTH_INCHES,
	ucp.DEPTH_INCHES,
	ucp.WEIGHT_OUNCES,
	ucp.WEIGHT_POUNDS,
	p.COD_PRODUTO||'-'||c.COD_COR||'-' AS PRODUTO_SKU2,
	p.COD_PRODUTO||'-'||c.COD_COR||'-'||t.TAMANHO AS PRODUTO_SKU3,
	p.PRODUTO||'_'||c.COR||'_'||'0'||'_'||t.TAMANHO AS PRODUTO_ID_INTERNO
FROM PRODUTOS p 
JOIN COR_PROD cp ON p.PRODUTO = cp.PRODUTO
JOIN CORES c ON cp.COR = c.COR
JOIN TAMANHOS t ON t.GRADE = p.GRADE
LEFT JOIN GRADES g ON g.GRADE = p.GRADE
LEFT JOIN CODIGO_BARRAS cb ON p.PRODUTO = cb.PRODUTO AND c.COR = cb.COR AND t.TAMANHO = cb.TAMANHO
LEFT JOIN COLECOES c2 ON c2.COLECAO = p.COLECAO 
LEFT JOIN SUBCOLECOES s ON s.SUBCOLECAO = p.SUBCOLECAO 
LEFT JOIN CATEGORIASP c3 ON c3.CATEGORIA = p.CATEGORIA 
LEFT JOIN MARCAS m ON m.MARCA = p.MARCA
LEFT JOIN GRUPOS g2 ON g2.GRUPO = p.GRUPO
LEFT JOIN DIVISOES d ON d.DIVISAO = p.DIVISAO
LEFT JOIN FAIXAS_VALORES fv ON fv.FAIXA_VALOR = p.FAIXA_VALOR
LEFT JOIN DEPARTAMENTOS d2 ON d2.DEPARTAMENTO = p.DEPARTAMENTO 
LEFT JOIN TIPOS t2 ON t2.TIPO = p.TIPO
LEFT JOIN CLASSIFICACAO_FIS cf ON cf.CLASSIFICACAO_FIS = p.CLASSIFICACAO_FIS
LEFT JOIN CORES_TRADUCAO ct ON c.COR = ct.COR 
LEFT JOIN TAMANHOS_TRADUCAO tt ON t.TAMANHO = tt.TAMANHO
LEFT JOIN USR_CADASTROS_PRODUTOS ucp ON ucp.PRODUTO = p.PRODUTO 
LEFT JOIN USR_CORES_COLLECTION_THEME ucct ON ucct.COR = c.COR
LEFT JOIN USR_CORES_PRIMARIAS ucp2 ON ucp2.COR = c.COR
LEFT JOIN USR_CORES_SECUNDARIAS ucs ON ucs.COR = c.COR
LEFT JOIN USR_ESTAMPA_ELEMENTO_PRIMARIO ueep ON ueep.COR = c.COR
LEFT JOIN USR_ESTAMPA_ELEMENTO_SECUNDARIO uees ON uees.COR = c.COR
LEFT JOIN USR_PRODUTOS_LINHA_PERFORMANCE uplp ON uplp.PRODUTO = p.PRODUTO 
LEFT JOIN USR_PRODUTOS_ORIENTACAO upo ON upo.PRODUTO = p.PRODUTO
LEFT JOIN USR_AUTHEN_COLECOES uac ON uac.COLECAO = c2.COLECAO 
LEFT JOIN USR_AUTHEN_DIVISOES uad ON uad.DIVISAO = d.DIVISAO 
LEFT JOIN USR_AUTHEN_SUBCOLECOES uas ON uas.SUBCOLECAO = s.SUBCOLECAO 
LEFT JOIN USR_AUTHEN_TIPOS uat ON uat.TIPO = t2.TIPO
