-- VITRINE DE PRODUTOS
SELECT 
	vps.VITRINE_PRODUTO_SKU,
	vps.VITRINE AS VITRINE_ID,
	v.DESCRICAO,
	vps.PRODUTO AS PRODUTO_ID,
	p.COD_PRODUTO,
	vps.COR AS COR_ID,
	c.COD_COR,
	vps.TAMANHO,
	c.DESCRICAO AS COR_NOME,
	vps.INCLUIR,
	vps.BLOQUEADO,
	vps.OBSERVACAO,
	vps.IMPORTADO,
	vps.INTEGRAR,
	vps.DATA_ENVIO,
	vps.DATA_ALTERACAO,
	vps.ID_EXTERNO,
	vps.ID_EXTERNO_PRODUTO,
	cb.BARRA AS GTIN,
	p.COD_PRODUTO||'-'||c.COD_COR||'-'||vps.TAMANHO AS PRODUTO_SKU3,
	p.PRODUTO||'_'||c.COR||'_'||'0'||'_'||vps.TAMANHO AS PRODUTO_ID_INTERNO
FROM VITRINE_PRODUTOS_SKU vps
JOIN PRODUTOS p ON vps.PRODUTO = p.PRODUTO
JOIN CORES c ON vps.COR = c.COR
JOIN VITRINE v ON vps.VITRINE = v.VITRINE 
LEFT JOIN CODIGO_BARRAS cb ON p.PRODUTO = cb.PRODUTO AND c.COR = cb.COR AND vps.TAMANHO = cb.TAMANHO
