--MovimentosEntradas
SELECT 
	m.ROMANEIO,
	m.CANCELADA,
	f.COD_FILIAL,
	f.FANTASIA AS CANAL,
	m.TIPO_OPERACAO AS TIPO_EVENTO,
	e.DESCRICAO AS EVENTO_DESC,
	m."DATA",
	f2.FORNECEDOR AS FORNECEDOR_ID,
	f2.COD_FORNECEDOR AS FORNECEDOR_CODIGO,
	f2.NOME AS FORNECEDOR,
	f2.CNPJ AS FORNECEDOR_CNPJ,
	p.COD_PRODUTO,
	c2.COD_COR,
	pe.TAMANHO,
	pe.QUANTIDADE,
	m.FILIAL_DESTINO,
	p.COD_PRODUTO||'-'||c2.COD_COR||'-' AS PRODUTO_SKU2,
	p.COD_PRODUTO||'-'||c2.COD_COR||'-'||pe.TAMANHO AS PRODUTO_SKU3,
	p.PRODUTO||'_'||c2.COR||'_'||'0'||'_'||pe.TAMANHO AS PRODUTO_ID_INTERNO,
	m.COD_OPERACAO,
	m.TIPO_OPERACAO 
FROM MOVIMENTO m
JOIN FILIAIS f ON f.FILIAL = m.FILIAL
JOIN EVENTOS e ON e.EVENTO = m.EVENTO
LEFT JOIN FORNECEDORES f2 ON f2.FORNECEDOR = m.FORNECEDOR
LEFT JOIN PRODUTOS_EVENTOS pe ON pe.COD_OPERACAO = m.COD_OPERACAO AND pe.TIPO_OPERACAO = m.TIPO_OPERACAO
LEFT JOIN PRODUTOS p ON pe.PRODUTO = p.PRODUTO
LEFT JOIN CORES c2 ON pe.COR = c2.COR
WHERE m.TIPO_OPERACAO IN ('E','T')
ORDER BY m."DATA" ASC
