--Fornecedores
SELECT
	f.GERADOR,
	f.COD_FORNECEDOR,
	f.NOME,
	f.FANTASIA,
	f.CNPJ,
	f.IE,
	f.E_MAIL,
	ec.ESTADO,
	ec.CIDADE,
	m.COD_IBGE,
	ec.BAIRRO,
	ec.LOGRADOURO,
	ec.NUMERO,
	ec.COMPLEMENTO,
	ec.CEP,
	f.BANCO,
	f.CC_CREDITO,
	f.CC_DEBITO,
	cc.CODIGO,
	cc.NOME
FROM FORNECEDORES f
LEFT JOIN ENDERECOS_CADASTRO ec ON ec.GERADOR = f.GERADOR AND ec.ENDERECO_NOTA = 'T'
LEFT JOIN MUNICIPIOS m ON m.NOME_SEM_ACENTO = ec.CIDADE AND m.UF = ec.ESTADO
LEFT JOIN CENTRO_CUSTOS cc ON cc.CENTRO_CUSTOS = f.CENTRO_CUSTOS
