--fMovimentos
SELECT 
	m.ROMANEIO,
	m."DATA" AS DATA_MOVIMENTO,
	m.CANCELADA,
	f.COD_FILIAL,
	f.FANTASIA AS FILIAL_FANTASIA,
	m.TIPO_OPERACAO AS TIPO_EVENTO,
	e.CODIGO AS EVENTO_COD,
	e.DESCRICAO AS EVENTO_DESC,
	c3.NAT_OPERACAO AS CFOP,
	c3.DESCRICAO AS DESC_CFOP,
	nf.NUMERO_NOTA AS NF,
	nf."DATA" AS DATA_NF,
	nf.STATUS AS STATUS_NF,
	f2.FORNECEDOR AS FORNECEDOR_ID,
	f2.COD_FORNECEDOR AS FORNECEDOR_CODIGO,
	f2.NOME AS FORNECEDOR_RAZAO_SOCIAL,
	f2.CNPJ AS FORNECEDOR_CNPJ,
	m.CLIENTE,
	nf.COD_ENDERECO,
	gl.COD_GRUPO AS COD_GRUPO_LOJA,
	gl.NOME AS GRUPO_LOJA_FANTASIA,
	c.COD_CLIENTE,
	c.NOME AS CLIENTE_RAZAO_SOCIAL,
	c.FANTASIA AS CLIENTE_FANTASIA,
	c.CNPJ,
	c.CPF,
	r.COD_REPRESENTANTE,
	r.NOME AS REPRESENTANTE_RAZAO_SOCIAL,
	r.E_MAIL AS REPRESENTANTE_EMAIL,
	tp.COD_TPRECO,
	tp.DESCRICAO AS TABELA_DE_PRECO,
	cp.CODIGO AS COD_CONDICOES_PGTO,
	cp.DESCRICAO AS CONDICOES_PGTO,
	p.COD_PRODUTO,
	c2.COD_COR,
	pe.TAMANHO,
	tp.COD_TPRECO || p.COD_PRODUTO AS KEY_TABPRICE,
	pe.PEDIDO,
	pv.COD_PEDIDOV,
	pe.QUANTIDADE,
	pe.PRECO,
	pe.IT_VALOR_BRUTO,
	pe.IT_VALOR_DESCONTO,
	pe.IT_VALOR_CORTESIA,
	pe.IT_VALOR_LIQUIDO,
	pe.V_ICMS,
	pe.V_PIS,
	pe.V_COFINS,
	pe.V_IPI,
	pe.IT_VALOR_FRETE,
	p.COD_PRODUTO||'-'||c2.COD_COR||'-' AS PRODUTO_SKU2,
	p.COD_PRODUTO||'-'||c2.COD_COR||'-'||pe.TAMANHO AS PRODUTO_SKU3,
	p.PRODUTO||'_'||c2.COR||'_'||'0'||'_'||pe.TAMANHO AS PRODUTO_ID_INTERNO
FROM MOVIMENTO m
JOIN FILIAIS f ON f.FILIAL = m.FILIAL
JOIN EVENTOS e ON e.EVENTO = m.EVENTO
LEFT JOIN FORNECEDORES f2 ON f2.FORNECEDOR = m.FORNECEDOR
LEFT JOIN CLIENTES c ON c.CLIENTE = m.CLIENTE
LEFT JOIN GRUPO_LOJAS gl ON gl.GRUPO_LOJA = c.GRUPO_LOJA
LEFT JOIN REPRESENTANTES r ON r.REPRESENTANTE = m.REPRESENTANTE
LEFT JOIN NF nf ON m.COD_OPERACAO = nf.COD_OPERACAO AND m.TIPO_OPERACAO = nf.TIPO_OPERACAO
LEFT JOIN PRODUTOS_EVENTOS pe ON pe.COD_OPERACAO = m.COD_OPERACAO AND pe.TIPO_OPERACAO = m.TIPO_OPERACAO
LEFT JOIN PRODUTOS p ON pe.PRODUTO = p.PRODUTO
LEFT JOIN CORES c2 ON pe.COR = c2.COR
LEFT JOIN CONDICOES_PGTO cp ON m.CONDICOES_PGTO = cp.CONDICOES_PGTO
LEFT JOIN TABELAS_PRECO tp ON tp.TABELA = m.TABELA
LEFT JOIN CFOP c3 ON c3.CFOP = pe.CFOP
LEFT JOIN PEDIDO_VENDA pv ON pe.PEDIDO = pv.PEDIDOV
