--Estoque
SELECT 
	e.FILIAL AS FILIAL_ID,
	f.COD_FILIAL AS FILIAL_COD,
	f.FANTASIA AS FILIAL_FANTASIA,
	p.COD_PRODUTO AS PRODUTO_SKU1,
	c.COD_COR AS COR_CODIGO,
	e.TAMANHO AS TAMANHO,
	e.FISICO,
	e.EMPENHO,
	e.INDISPONIVEL,
	e.PODER_TERCEIRO,
	e.SALDO,
	p.COD_PRODUTO||'-'||c.COD_COR||'-' AS PRODUTO_SKU2,
	p.COD_PRODUTO||'-'||c.COD_COR||'-'||e.TAMANHO AS PRODUTO_SKU3,
	p.PRODUTO||'_'||c.COR||'_'||'0'||'_'||e.TAMANHO AS PRODUTO_ID_INTERNO
FROM ESTOQUES e 
JOIN FILIAIS f ON f.FILIAL = e.FILIAL
LEFT JOIN PRODUTOS p ON p.PRODUTO = e.PRODUTO
LEFT JOIN CORES c ON e.COR = c.COR
ORDER BY f.COD_FILIAL ASC
