--MovimentosSinteticoEntrada
SELECT
	m.ROMANEIO,
	f.COD_FILIAL,
	f.FANTASIA AS FILIAL_FANTASIA,
	m.TIPO_OPERACAO AS TIPO_EVENTO,
	m."DATA",
	m.CANCELADA,
	e.DESCRICAO AS EVENTO,
	COUNT(m.ROMANEIO) AS QTD_MOVIMENTOS, 
	SUM (pe.QUANTIDADE) AS QUANTIDADE,
	SUM (pe.IT_VALOR_BRUTO) AS VALOR_BRUTO,
	SUM (pe.IT_VALOR_DESCONTO) AS VALOR_DESCONTO,
	SUM (pe.IT_VALOR_CORTESIA) AS VALOR_DESCONTO2,
	SUM (pe.IT_VALOR_LIQUIDO) AS VALOR_LIQUIDO,
	SUM (pe.V_ICMS) AS ICMS,
	SUM (pe.V_PIS) AS PIS,
	SUM (pe.V_COFINS) AS COFINS,
	SUM (pe.V_IPI) AS IPI
FROM MOVIMENTO m
JOIN FILIAIS f ON f.FILIAL = m.FILIAL
JOIN EVENTOS e ON e.EVENTO = m.EVENTO 
LEFT JOIN FORNECEDORES f2 ON f2.FORNECEDOR = m.FORNECEDOR
LEFT JOIN CLIENTES c ON c.CLIENTE = m.CLIENTE 
LEFT JOIN PRODUTOS_EVENTOS pe ON pe.COD_OPERACAO = m.COD_OPERACAO AND pe.TIPO_OPERACAO = m.TIPO_OPERACAO
LEFT JOIN PRODUTOS p ON pe.PRODUTO = p.PRODUTO
WHERE e.EVENTO IN (2322,20220,8) AND m.CANCELADA = 'F'
GROUP BY m.ROMANEIO, f.COD_FILIAL, f.FANTASIA, m.TIPO_OPERACAO, m."DATA", m.CANCELADA, e.DESCRICAO

