-- VISUALIZAR LOG DE PEDIDO
SELECT * FROM vitrine_log WHERE cod_pedidov = 'VT-XYZ' ORDER BY DATA DESC 

-- 1) SELECT EM DADOS DO PEDIDO
SELECT 
	DISTINCT (p.PREFATURAMENTO) AS PREFAT_ID
	,p.NUMERO AS PREFAT_COD
	,p.PEDIDOV AS PEDIDO_ID
	,pv.COD_PEDIDOV
	,nf.SERIE
	,nf.NOTA
	,nf.STATUS
	,nf.IDNFE
	,nf.MENSAGEMNFE
	,s.SAIDA
FROM PREFATURAMENTOS p
LEFT JOIN PEDIDO_VENDA pv ON p.PEDIDOV = pv.PEDIDOV
LEFT JOIN PRODUTO_PREFAT pp ON p.PREFATURAMENTO = pp.PREFATURAMENTO
LEFT JOIN SAIDAS s ON pp.SAIDA = s.SAIDA
LEFT JOIN NF nf ON nf.TIPO_OPERACAO = 'S' AND nf.COD_OPERACAO = s.SAIDA
WHERE 
	pp.SAIDA IS NOT NULL
	AND pv.COD_PEDIDOV = 'VT-837470'

-- 2) UPDATE TABELA NF COM PROTOCOLO DA SEFAZ
UPDATE
	NF nf 
SET
	IDPROTOCOLO = 
	,MENSAGEMNFE = 'Autorizado o uso da NF-e'
	,STATUS = 100
WHERE
	NOTA = 

-- 3) UPDATE - UTILIZAR O COD OPERACAO PARA ATUALIZAR O CONTEUDO(XML)
UPDATE 
	DOCUMENTOS d 
SET 
	d.CONTEUDO = ''
WHERE 
	d.ORIGEM = 
