--Representantes
SELECT 
	r.GERADOR,
	r.REPRESENTANTE,
	r.COD_REPRESENTANTE,
	r.NOME AS REPRESENTANTE_RAZAO_SOCIAL,
	r.FANTASIA AS REPRESENTANTE_FANTASIA,
	r.CNPJ,
	r.E_MAIL AS REPRESENTANTE_EMAIL,
	urmc.CODIGO AS COD_MACRO_COBERURA_CONSULTOR,
	urmc.DESCRICAO AS MACRO_COBERTURA_CONSULTOR,
	urmc2.CODIGO AS COD_MICRO_COBERTURA_CONSULTOR,
	urmc2.DESCRICAO AS MICRO_COBERTURA_CONSULTOR,
	ec.DDD,
	ec.FONE,
	ec.LOGRADOURO,
	ec.NUMERO,
	ec.COMPLEMENTO,
	ec.BAIRRO,
	ec.CIDADE,
	ec.ESTADO,
	ec.CEP,
	m.COD_IBGE
FROM REPRESENTANTES r 
LEFT JOIN USR_REP_MACRO_COBERTURA urmc ON urmc.REPRESENTANTE = r.REPRESENTANTE
LEFT JOIN USR_REP_MICRO_COBERTURA urmc2 ON urmc2.REPRESENTANTE = r.REPRESENTANTE
LEFT JOIN ENDERECOS_CADASTRO ec ON ec.GERADOR = r.GERADOR
LEFT JOIN MUNICIPIOS m ON m.NOME_SEM_ACENTO = ec.CIDADE AND m.UF = ec.ESTADO
WHERE r.COD_REPRESENTANTE <> 'INDEFINIDO' AND ec.ENDERECO = 0
