SELECT
	m.ROMANEIO,
	f.COD_FILIAL,
	f.FANTASIA AS CANAL,
	m.TIPO_OPERACAO AS TIPO_EVENTO,
	e.DESCRICAO AS EVENTO,
	m."DATA",
	m.CANCELADA,
	nf.STATUS,
	ns.DESCRICAO,
	COUNT(DISTINCT ve.VOLUME_EVENTO) AS VOLUMES_NOTA,
	SUM (pe.QUANTIDADE) AS QUANTIDADE,
	SUM (pe.IT_VALOR_BRUTO) AS VALOR_BRUTO,
	SUM (pe.IT_VALOR_DESCONTO) AS VALOR_DESCONTO,
	SUM (pe.IT_VALOR_CORTESIA) AS VALOR_DESCONTO2,
	SUM (pe.IT_VALOR_LIQUIDO) AS VALOR_LIQUIDO,
	SUM (pe.V_ICMS) AS ICMS,
	SUM (pe.V_PIS) AS PIS,
	SUM (pe.V_COFINS) AS COFINS,
	SUM (pe.V_IPI) AS IPI
FROM MOVIMENTO m
JOIN FILIAIS f ON f.FILIAL = m.FILIAL
JOIN EVENTOS e ON e.EVENTO = m.EVENTO 
LEFT JOIN FORNECEDORES f2 ON f2.FORNECEDOR = m.FORNECEDOR
LEFT JOIN CLIENTES c ON c.CLIENTE = m.CLIENTE 
LEFT JOIN NF nf ON m.COD_OPERACAO = nf.COD_OPERACAO AND m.TIPO_OPERACAO = nf.TIPO_OPERACAO
LEFT JOIN NF_STATUS ns ON ns.STATUS = nf.STATUS
LEFT JOIN PRODUTOS_EVENTOS pe ON pe.COD_OPERACAO = m.COD_OPERACAO AND pe.TIPO_OPERACAO = m.TIPO_OPERACAO
LEFT JOIN PRODUTOS p ON pe.PRODUTO = p.PRODUTO
LEFT JOIN VOLUMES_EVENTO ve ON ve.COD_OPERACAO = m.COD_OPERACAO AND ve.TIPO_OPERACAO = m.TIPO_OPERACAO
WHERE nf.STATUS = 100 AND m.EVENTO = 20301
GROUP BY m.ROMANEIO, f.COD_FILIAL, f.FANTASIA, m.TIPO_OPERACAO, e.DESCRICAO, m."DATA", m.CANCELADA, nf.STATUS,nf.VOLUME, ns.DESCRICAO 
