--CondicoesTiposPgto
SELECT
	cp.CONDICOES_PGTO AS CONDICOES_PGTO_ID,
	cp.CODIGO AS CONDICOES_PGTO_COD,
	cp.DESCRICAO AS CONDICOES_PGTO_DESC,
	cp.PRAZO_MEDIO,
	cp.PRAZO AS PRAZO_PRIMEIRA_PCL,
	cp.TIPO_PGTO AS TIPOS_PGTOS_ID,
	tp.DESCRICAO AS TIPOS_PGTOS_DESC
FROM CONDICOES_PGTO cp 
JOIN TIPOS_PGTOS tp ON tp.TIPO_PGTO = cp.TIPO_PGTO
ORDER BY cp.CODIGO ASC
